spring:
  datasource:
    url: jdbc:postgresql://${FM_DB_HOSTNAME}:${FM_DB_PORT:5432}/${FM_DB_NAME}
    username: ${FM_DB_USERNAME}
    password: ${FM_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${FM_KC_OAUTH_ISSUER_URI}
          jwk-set-uri: ${FM_KC_OAUTH_JWK_SET_URI}

server:
  port: ${FM_SERVER_PORT:8080}

