spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fm
    username: fm
    password: fm

  jpa:
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/fm
          jwk-set-uri: http://localhost:8081/realms/fm/protocol/openid-connect/certs

  graphql:
    graphiql:
      enabled: true
      path: /graphiql

server:
  port: 8085

