spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fm
    username: fm
    password: fm

  jpa:
    hibernate:
      ddl-auto: create-drop


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fm
          jwk-set-uri: http://localhost:8080/realms/fm/protocol/openid-connect/certs

server:
  port: 8085

